### ISSUE TITLE
App打不开一直死循环报错

### ISSUE THREAD

**Issue by 1322202454** [long8313002/SuperXml#4]
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.NoSuchFieldException: No field mFactorySet in class Landroid/view/LayoutInflater; (declaration of 'android.view.LayoutInflater' appears in /system/framework/framework.jar!classes3.dex)
        at java.lang.Class.getDeclaredField(Native Method)
        at com.zhangzheng.superxml.library.SuperXml.setLayoutInflateAllowState(SuperXml.kt:50)
        at com.zhangzheng.superxml.library.SuperXml.hookActivityLayout(SuperXml.kt:38)
        at com.zhangzheng.superxml.library.SuperXml.access$hookActivityLayout(SuperXml.kt:14)
        at com.zhangzheng.superxml.library.SuperXml$init$1.onActivityCreated(SuperXml.kt:26)
        at android.app.Application.dispatchActivityCreated(Application.java:412)
        at android.app.Activity.dispatchActivityCreated(Activity.java:1202)
        at android.app.Activity.onCreate(Activity.java:1475)
        at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:154)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
        at com.yizhong.lib_base.base.BaseActivity.onCreate(BaseActivity.kt:39)
        at android.app.Activity.performCreate(Activity.java:7820)
        at android.app.Activity.performCreate(Activity.java:7809)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)

说是因为读取限制接口mFactorySet的问题    系统Android 10.0

**Comment by long8313002** [comment]
你好，这个是android私有api的访问限制导致的，可以这种方式绕过：https://github.com/tiann/FreeReflection
